export const GitHubEventTypes = {
  CommitCommentEvent: { name: 'Commit Comment', color: '#2f81f7' },
  CreateEvent: { name: 'Create', color: '#3fb950' },
  DeleteEvent: { name: 'Delete', color: '#f85149' },
  ForkEvent: { name: 'Fork', color: '#ffd33d' },
  GollumEvent: { name: 'Gollum', color: '#2f81f7' },
  IssueCommentEvent: { name: 'Issue Comment', color: '#ff9549' },
  IssuesEvent: { name: 'Issues', color: '#ffd33d' },
  MemberEvent: { name: 'Member', color: '#c9d1d9' },
  PublicEvent: { name: 'Public', color: '#c9d1d9' },
  PullRequestEvent: { name: 'Pull Request', color: '#7c72ff' },
  PullRequestReviewEvent: { name: 'Pull Request Review', color: '#ee5ab6' },
  PullRequestReviewCommentEvent: { name: 'Pull Request Comment', color: '#7c72ff' },
  PushEvent: { name: 'Push', color: '#2f81f7' },
  ReleaseEvent: { name: 'Release', color: '#2f81f7' },
  WatchEvent: { name: 'Watch', color: '#ee5ab6' },
};
